Merge r213491 - [cairo] error C2065: 'quality': undeclared identifier since r213412 https://bugs.webkit.org/show_bug.cgi?id=169240
Patch by Fujii Hironori <Hironori.Fujii@sony.com> on 2017-03-06
Reviewed by Ryosuke Niwa.

* platform/graphics/cairo/ImageBufferCairo.cpp:
(WebCore::ImageBuffer::toDataURL): Name the unnamed second argument 'quality'.

git-svn-id: http://svn.webkit.org/repository/webkit/releases/WebKitGTK/webkit-2.16@213820 268f45cc-cd09-0410-ab3c-d52691b4dbfc