[W32][GTK] GI fails due to W32-incompatible arguments to the scanner https://bugs.webkit.org/show_bug.cgi?id=143764
Patch by Руслан Ижбулатов <lrn1986@gmail.com> on 2015-04-15
Reviewed by Carlos Garcia Campos.

Use correct .la files as --library arguments for GI scanner

This way it plays well with W32 gobject-introspection library resolution
code.
Without that one would get things like:
ERROR: can't resolve libraries to shared libraries: webkitgtk-3.0, javascriptcoregtk-3.0

* GNUmakefile.am:

git-svn-id: http://svn.webkit.org/repository/webkit/releases/WebKitGTK/webkit-2.4@184504 268f45cc-cd09-0410-ab3c-d52691b4dbfc